services:
  alura-express-nodejs:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '.:/home/node/app'
    entrypoint: sh .docker/entrypoint.sh
    stdin_open: true 
    tty: true
